#!/bin/bash
# JohnFordTV's Panel Premium Script
# © Github.com/johndesu090
# Official Repository: https://github.com/johndesu090
# For Updates, Suggestions, and Bug Reports, Join to my Messenger Groupchat(VPS Owners): https://m.me/join/AbbHxIHfrY9SmoBO
# For Donations, Im accepting prepaid loads or GCash transactions:
# Smart: 09206200840
# Facebook: https://fb.me/johndesu090
# Thanks for using this script


if [[ $EUID -ne 0 ]]; then
 echo -e "[\e[31mError\e[0m] This script must be run as root, exiting..."
 exit 1
fi

source /etc/os-release
if [[ "$ID" != 'debian' ]]; then
 echo -e "[\e[31mError\e[0m] This script is for Debian instance only, exiting..."
 exit 1
elif [[ "$VERSION_ID" != '9' ]]; then
 echo -e "[\e[31mError\e[0m] This script is for Debian Stretch distribution only, exiting..."
 exit 1
fi

# VAR
MYIP=$(wget -qO- ipv4.icanhazip.com);

# Go to Root folder
cd

clear
echo ""
echo "I need to ask some questions before starting setup"
echo "You can leave the default option and just hit enter if you agree with the option"
echo ""
echo "First I need to know the new password of MySQL root user:"
read -p "Password: " -e -i johnfordtv DatabasePass
echo ""
echo "Finally, name the Database Name for OCS Panels"
echo " Please, use one word only, no special characters other than Underscore (_)"
read -p " Database Name: " -e -i redpanel DatabaseName
echo ""
echo "Okay, that's all I need. We are ready to setup your OCS Panels now"
read -n1 -r -p "Press any key to continue..."

#apt-get update
apt-get update -y
apt-get install build-essential expect -y

apt-get install -y mysql-server

#mysql_secure_installation
so1=$(expect -c "
spawn mysql_secure_installation; sleep 3
expect \"\";  sleep 3; send \"\r\"
expect \"\";  sleep 3; send \"Y\r\"
expect \"\";  sleep 3; send \"$DatabasePass\r\"
expect \"\";  sleep 3; send \"$DatabasePass\r\"
expect \"\";  sleep 3; send \"Y\r\"
expect \"\";  sleep 3; send \"Y\r\"
expect \"\";  sleep 3; send \"Y\r\"
expect \"\";  sleep 3; send \"Y\r\"
expect eof; ")
echo "$so1"
#\r
#Y
#pass
#pass
#Y
#Y
#Y
#Y

chown -R mysql:mysql /var/lib/mysql/
chmod -R 755 /var/lib/mysql/
# install nginx 5.6
apt-get -y install nginx php5.6 php5.6-fpm php5.6-cli php5.6-common php5.6-curl php5.6-mbstring php5.6-mysql php5.6-mcrypt php5.6-xml php5.6-ssh2
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup 
mv /etc/nginx/conf.d/vps.conf /etc/nginx/conf.d/vps.conf.backup 
wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/johndesu090/AutoScriptDeb8/master/Files/Nginx/nginx.conf" 
wget -O /etc/nginx/conf.d/johnfordtv.conf "https://raw.githubusercontent.com/johndesu090/AutoScriptDeb8/master/Files/Nginx/vps.conf" 
sed -i 's/cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php5.6/fpm/php.ini 
sed -i 's/listen = \/var\/run\/php5-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php5.6/fpm/pool.d/www.conf

useradd -m panel
mkdir -p /home/panel/html
rm /home/panel/html/index.html
echo "<?php phpinfo() ?>" > /home/panel/html/info.php
chown -R www-data:www-data /home/panel/html
chmod -R g+rw /home/panel/html
service php5.6-fpm restart
service nginx restart

apt-get -y install zip unzip
cd /home/panel/html
wget https://www.dropbox.com/s/91wubkz6kump8b2/redpanel.zip
unzip redpanel.zip
rm -f redpanel.zip
chown -R www-data:www-data /home/panel/html
chmod -R g+rw /home/panel/html



#grant privileges on database to root
so2=$(expect -c "
spawn mysql -u root -p $DatabaseName < /home/panel/html/database/sshpanel.sql; sleep 3
expect \"\";  sleep 3; send \"$DatabasePass\r\"
expect \"\";  sleep 3; send \"CREATE DATABASE IF NOT EXISTS $DatabaseName;EXIT;\r\"
expect \"\";  sleep 3; send \"GRANT ALL ON $DatabaseName.* TO 'root'@"localhost";EXIT;\r\"
expect \"\";  sleep 3; send \"FLUSH PRIVILEGES;EXIT;\r\"
expect eof; ")
echo "$so2"
#pass

#modify database
sed -i "s|DB_PASSWORD=""|DB_PASSWORD="$DatabasePass"|g" /home/panel/html/system/.env
sed -i "s|sshpanel_rev|$DatabaseName|g" /home/panel/html/system/.env

clear
echo "Open Browser, access http://$MYIP/ and fill up the install form!"
echo "Click Install and wait for the process to finish!"

sleep 3
echo ""
read -p "If the above step has been done, please Press [Enter] key to continue...."
echo ""
read -p "If you really believe the above step has been done, please Press [Enter] key to continue..."
echo ""

cd
rm -f /root/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile


# info
#clear
#echo "=======================================================" | tee -a log-install.txt
#echo "Please login Reseller Panel at http://$MYIP:85" | tee -a log-install.txt
#echo "" | tee -a log-install.txt
#echo "Auto Script Installer OCS Panels Mod by Clrkz"  | tee -a log-install.txt
#echo "             (http://bytehax.blogspot.com/ - fb.com/143Clarkz)           "  | tee -a log-install.txt
#echo "" | tee -a log-install.txt
#echo "Thanks " | tee -a log-install.txt
#echo "" | tee -a log-install.txt
#echo "Installation Log --> /root/log-install.txt" | tee -a log-install.txt
#echo "=======================================================" | tee -a log-install.txt
cd ~/

#rm -f /root/ocspanel.sh
